"""
generates the FMCSC_FRZFILE file to constrain DOF.
We use al = sign to mark a residue that can move but was in the alignment
"""
# I leave one more residue free than that of the alignment. Marked as '='
alignment="""
MLEARFQQAALLKKLLDAIKELVTDANFDCNDNGISLQAMDSSHVALVSMLIKSDGFEPY
RCDRNIALGINLNALSKVLRCAQNEDLVTLKAEDTPEVLNLVFESEKNDRISDYDVKLMD
IDQEHLGIPDIEYDATITMPAAEFQRITRDLLTLSDSVTINASKEGVRFSCKGDIGNGST
TLKQHTDLSDQDQSIEISLTQAVTLTFSLKYLAQFTKATPLATRVTLSMSNDVPLLVEYK
MESGFLRFYLAP=-------/
MLEARFQQAALLKKLLDAIKELVTDANFDCNDNGISLQAMDSSHVALVSMLIKSDGFEPY
RCDRNIALGINLNALSKVLRCAQNEDLVTLKAEDTPEVLNLVFESEKNDRISDYDVKLMD
IDQEHLGIPDIEYDATITMPAAEFQRITRDLLTLSDSVTINASKEGVRFSCKGDIGNGST
TLKQHTDLSDQDQSIEISLTQAVTLTFSLKYLAQFTKATPLATRVTLSMSNDVPLLVEYK
MESGFLRFYLAP=-------/
MLEARFQQAALLKKLLDAIKELVTDANFDCNDNGISLQAMDSSHVALVSMLIKSDGFEPY
RCDRNIALGINLNALSKVLRCAQNEDLVTLKAEDTPEVLNLVFESEKNDRISDYDVKLMD
IDQEHLGIPDIEYDATITMPAAEFQRITRDLLTLSDSVTINASKEGVRFSCKGDIGNGST
TLKQHTDLSDQDQSIEISLTQAVTLTFSLKYLAQFTKATPLATRVTLSMSNDVPLLVEYK
MESGFLRFYLAP=-------/
--------------------------------------------------==GSLMDV==
------------------------------------------------------------
----
"""
alignment = alignment.replace('\n', '')
alignment = alignment.replace("/", "")
fileout = open("constraints_resi.inp", 'w')
fileout.write("R\n")
for num, resi in enumerate(alignment):
    if resi !='-' and resi !='=':
        fileout.write(str(num+1))
        fileout.write(" ALL\n")

